apiVersion: v1
kind: Secret
metadata:
  name: {{ include "idas.fullname" . }}
  labels:
    {{- include "idas.labels" . | nindent 4 }}
stringData:
  CLIENT_SECRET: "{{ required "CLIENTSECRET is required" .Values.env.CLIENTSECRET }}"
  SMTP_PASSWORD: "{{ .Values.env.SMTPPASSWORD }}"