apiVersion: v1
kind: Service
metadata:
  name: {{ include "idas.fullname" . }}
  labels:
    {{- include "idas.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: idas
  selector:
    {{- include "idas.selectorLabels" . | nindent 4 }}
